version: '3.8'
services:
  zigbee2mqtt:
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ${APP_DATA_DIR}/data/:/app/data
      - '/run/udev:/run/udev:ro'
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Singapore
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0