version: '3.8'

services:
  app_proxy:
    environment:
      APP_HOST: home-automation-mqtt-broker_web_1
      APP_PORT: 1883

  web:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - './mosquitto-data:/mosquitto'
    ports:
      - '1883:1883'
      - '9001:9001'
    command: 'mosquitto -c /mosquitto-no-auth.conf'
    environment:
      - TZ=Asia/Singapore
