version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:2.0@sha256:090d745b6435d10a31acb82eee999ec36a2d7f416cc4f578c0a298c42af2ea14
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/mosquitto-data:/mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
#    command: 'mosquitto -c /mosquitto-no-auth.conf'