version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/mosquitto-data:/mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'
#    command: 'mosquitto -c /mosquitto-no-auth.conf'